# Generated by Django 4.2.29 on 2026-03-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.TextField()),
                ('tabs', models.CharField(max_length=400)),
                ('difficulty', models.TextField()),
            ],
        ),
    ]
